### ISSUE TITLE
explore/みつけるへの対応

### ISSUE THREAD

**Issue by iharakazuki** [ikakonbu/Misskey-TL-Filter#8]
exploreページ（ハイライト）における対応というのは検討されていますか？
可能でしたら是非対応していただきたいです。

**Comment by ikakonbu** [comment]
@iharakazuki ホームやローカルみたいに、みつける画面にも個別のTL設定が欲しい、という感じですかね？

**Comment by iharakazuki** [comment]
その認識で合っています。かなり特殊な使い方であることは理解していますが…

**Comment by ikakonbu** [comment]
とりあえず実装できました
他にいくつか修正があるのでそれが完了したらリリースしようと思います


https://github.com/ikakonbu/Misskey-TL-Filter/assets/82440954/6778d6a8-738e-406e-8782-9f25e75b6f5c
